export const WINDOWS_WORDS = [
	"New folder",
	"New folder (2)",
	"New folder (3)",
	"New folder (4)",
	"New folder (5)",
	"New folder - Copy",
	"New folder - Copy (2)",
	"New folder (2) - Copy",
	"Copy of final",
	"Copy of Copy of final",
	"final",
	"FINAL",
	"Final",
	"final final",
	"final FINAL",
	"FINAL FINAL",
	"final (1)",
	"final (2)",
	"final (3)",
	"final v2",
	"final v3",
	"final v2 (1)",
	"final REAL",
	"final real final",
	"final for real",
	"final for real this time",
	"final DO NOT EDIT",
	"final approved",
	"final approved v2",
	"final sent",
	"final sent (1)",
	"final printed",
	"Untitled",
	"Untitled (1)",
	"Untitled (2)",
	"Untitled folder",
	"Untitled folder (2)",
	"Untitled document",
	"Untitled document (1)",
	"Untitled - Copy",
	"Documents",
	"My Documents",
	"Old Documents",
	"Documents - Copy",
	"Documents (old)",
	"Documents backup",
	"Documents 2019",
	"Documents misc",
	"Downloads",
	"Downloads (old)",
	"Old Downloads",
	"Downloads - Copy",
	"Downloads sort later",
	"Downloads to sort",
	"Downloads misc",
	"Downloads keep",
	"Desktop stuff",
	"Desktop old",
	"Old Desktop",
	"Desktop cleanup",
	"Desktop 2019",
	"Desktop 2020",
	"Desktop backup",
	"Desktop misc",
	"Pictures",
	"My Pictures",
	"Old Pictures",
	"Pictures - Copy",
	"Photos",
	"Photos (old)",
	"Photos misc",
	"Photos to sort",
	"Videos",
	"My Videos",
	"Old Videos",
	"Music",
	"My Music",
	"Old Music",
	"Recordings",
	"Voice memos",
	"Work",
	"Work stuff",
	"Work old",
	"Work (old)",
	"Work - Copy",
	"Work backup",
	"Work misc",
	"Work 2019",
	"Personal",
	"Personal stuff",
	"Personal old",
	"Personal - Copy",
	"Private",
	"Private stuff",
	"Private (do not open)",
	"Private backup",
	"backup",
	"Backup",
	"BACKUP",
	"backup (1)",
	"backup (2)",
	"backup old",
	"backup of backup",
	"Backup - Copy",
	"old",
	"OLD",
	"Old",
	"old stuff",
	"Old stuff",
	"OLD STUFF",
	"old old",
	"older",
	"stuff",
	"Stuff",
	"STUFF",
	"stuff (1)",
	"stuff (2)",
	"more stuff",
	"misc stuff",
	"random stuff",
	"misc",
	"Misc",
	"MISC",
	"misc (1)",
	"misc (2)",
	"misc old",
	"misc misc",
	"miscellaneous",
	"temp",
	"Temp",
	"TEMP",
	"tmp",
	"temp (1)",
	"temp (2)",
	"temp delete later",
	"temp keep",
	"DO NOT DELETE",
	"do not delete",
	"Do Not Delete",
	"DO NOT DELETE (1)",
	"DO NOT TOUCH",
	"do not touch",
	"DONT DELETE",
	"dont delete",
	"IMPORTANT",
	"Important",
	"important",
	"IMPORTANT (1)",
	"VERY IMPORTANT",
	"very important",
	"URGENT",
	"urgent",
	"To do",
	"TODO",
	"todo",
	"To sort",
	"to sort",
	"TO SORT",
	"Sort later",
	"sort later",
	"Archive",
	"archive",
	"ARCHIVE",
	"Archive (1)",
	"Archive old",
	"Archived",
	"archived",
	"Archives",
	"Scans",
	"scans",
	"Scan",
	"Scanned documents",
	"Scanned",
	"scan (1)",
	"scan (2)",
	"Scans - Copy",
	"Receipts",
	"receipts",
	"Receipts 2019",
	"Receipts 2020",
	"Invoices",
	"invoices",
	"Invoices old",
	"Invoices (paid)",
	"Taxes",
	"taxes",
	"Taxes 2019",
	"Taxes 2020",
	"Tax stuff",
	"tax stuff",
	"Tax documents",
	"Tax (old)",
	"Projects",
	"projects",
	"Project",
	"project",
	"Project (old)",
	"Old projects",
	"Side projects",
	"Project - Copy",
	"School",
	"school",
	"School stuff",
	"Uni",
	"University",
	"College",
	"Homework",
	"Assignments",
	"Games",
	"games",
	"Game saves",
	"Saves",
	"Mods",
	"mods",
	"Screenshots",
	"screenshots",
	"Installers",
	"installers",
	"Setup files",
	"setup",
	"Drivers",
	"drivers",
	"Software",
	"Programs",
	"Fonts",
	"fonts",
	"Icons",
	"icons",
	"Wallpapers",
	"wallpapers",
	"Templates",
	"templates",
	"Shortcuts",
	"shortcuts",
	"Links",
	"links",
	"Bookmarks",
	"bookmarks",
	"Notes",
	"notes",
	"Recipes",
	"recipes",
	"Travel",
	"travel",
	"Holiday",
	"holiday",
	"Wedding",
	"wedding",
	"Resume",
	"resume",
	"CV",
	"cv",
	"Resume (old)",
	"Resume final",
	"CV final",
	"CV final final",
];
